"""add is_payed field

Revision ID: 9daffa5f218f
Revises: b114bf9a52d7
Create Date: 2025-06-04 20:51:11.540604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9daffa5f218f'
down_revision: Union[str, None] = 'b114bf9a52d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_message_id'), table_name='user_message')
    op.drop_table('user_message')
    op.add_column('chat_user', sa.Column('is_payed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_user', 'is_payed')
    op.create_table('user_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('telegram_message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_message_pkey'))
    )
    op.create_index(op.f('ix_user_message_id'), 'user_message', ['id'], unique=False)
    # ### end Alembic commands ###
