from backend.core.domain.schemas import ChatUserDTO, ChatUserCreationDTO


class Storage:
    async def get_chat_user_by_telegram_id(self, telegram_id: int) -> ChatUserDTO | None: ...
    async def get_user_by_telegram_id(self, telegram_id: int) -> ChatUserDTO | None: ...
    async def create_chat_user(self, chat_user: ChatUserCreationDTO) -> ChatUserDTO: ...